---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    apt_cache_valid_time: 300
    gnupg_default_cache_ttl: 3600
    gnupg_max_cache_ttl: 86400
    env_files_path: "{{ ansible_user_dir }}/.env-files.d"
  tasks:
    - name: "Include mtik00.gnupg"
      ansible.builtin.include_role:
        name: "mtik00.gnupg"
